### ISSUE TITLE
Plogg meter

### ISSUE THREAD

**Issue by miguelaferreira** [cupertino/ectools#2]
I'm trying to calibrate ectools but I can't seem to find a Plogg meter anywhere. Although the we is full of references to Plogg meters all the websites that are provided seem to be either closed or in use for other things.

Is it possible to calibrate ectools using some other meter? Say a Wattsup Pro?

**Comment by cupertino** [comment]
Hello Miguel,

Did you put the plogg MAC in when instantiating the class? It needs such information in order to comunicate with the plogg. You can find it by running the ''hcitool scan'' command. You also need to be root to link via bluetooth to the device.

For the Wattsup meter, you need to program your own PowerMeter class. I we do not have access to this meter, we did not implemented it.

Cheers,

Leandro

**Comment by miguelaferreira** [comment]
Hi Leandro,

I don't have a plogg meter, not I can find where to buy one.

I do have a wattsup pro and my thought is now on coding a class that interacts with my meter. I will try that and let you know how it goes.

Cheers
-- Miguel

**Comment by cupertino** [comment]
I looked on wattsup website [1] and it seems you can either communicate with the meter using a serial connection via RS232 or through USB. They have APIs for both.

They also have an opensource linux program to fetch this data, maybe it can be a good starting point for implementing it. On the ectools documentation you will find an example how to create your own sensors. Please let me know if you face any difficulties.

Cheers,

Leandro

[1] https://www.wattsupmeters.com/secure/support.php
